basket/urls.py
from django.urls import path
from django.views.generic import TemplateView

from basket.views import AddToBasket, BasketDetailView, stripe_basket_checkout, SuccessView

app_name = 'basket'

urlpatterns = [
    path('add-to-basket', AddToBasket.as_view(), name="add_to_basket"),
    path('view-basket', BasketDetailView.as_view(), name="view_basket"),
    path('checkout-basket', stripe_basket_checkout, name="checkout_basket"),
    path('payment-error', TemplateView.as_view(template_name='basket/payment-error.html'), name="payment_error"),
    path('payment-success/<slug:slug>/', SuccessView.as_view(), name="payment_success"),
]

cms/urls.py
from django.urls import path

from cms.views import BlogListView, BlogDetailView

app_name = 'basket'

urlpatterns = [
path('', BlogListView.as_view(), name='blog_list'),
path('<int:pk>/', BlogDetailView.as_view(), name='blog_details'),
]

goshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from onboarding.views import PlanListView, OnboardingFormView, CreateOnboarding, SearchView


schema_view = get_schema_view(
    openapi.Info(
        title="Shopping API",
        default_version="v2",
        description="This Document has all the API endpoints for building setyour shop web pages.",
        terms_of_service="https://www.setyour.shop",
        contact=openapi.Contact(email="mohammed.sagheer95@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', SearchView.as_view(), name='search'),

    path('', PlanListView.as_view(), name='plans'),
    path("customer/", include('customers.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('onboarding/', include('onboarding.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('api/', include('restapis.urls')),
path(
            "swagger/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
    path('blogs/', include('cms.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls'))

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onboarding/urls.py
from django.urls import path
from django.views.generic import TemplateView

from onboarding.views import CreateOnboarding, OnboardingFormView

urlpatterns = [
    path('success/<slug:slug>/', CreateOnboarding.as_view(), name="create-onboarding"),
    path('<slug:slug>/', OnboardingFormView.as_view(), name='onboarding'),
]

products/urls.py
from django.urls import path

from products.views import AddProductFromPublicSchema


app_name = 'products'

urlpatterns = [
    path('add-product/', AddProductFromPublicSchema.as_view(), name='add_product'),
    # Add more product-related URL patterns as needed
]

onboarding/models.py
from django.db import models

# Create your models here.
from customers.abstract_model import TimeStamp
from customers.models import Client


class Plan(TimeStamp):
    BASIC = 'basic'
    ENTERPRISE = 'enterprise'
    PREMIUM = 'premium'
    plans = ((BASIC, 'Basic'), (ENTERPRISE, 'Enterprise'), (PREMIUM, 'Premium'))
    title = models.CharField(max_length=255, choices=plans)
    description = models.TextField()
    price = models.IntegerField()
    is_active = models.BooleanField(default=True)
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        verbose_name = "Plan"
        verbose_name_plural = "Plans"

    def __str__(self):
        return self.title

    def decription_array(self):
        return self.description.split("\n")


class Onboarding(TimeStamp):
    schema_name = models.CharField(max_length=255)
    domain_url = models.CharField(max_length=255)
    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    is_active = models.BooleanField(default=False)
    email = models.EmailField(null=True)
    plan = models.ForeignKey(Plan, null=True, related_name="onboarding_plan", on_delete=models.CASCADE)
    session_id = models.CharField(max_length=500, null=True, blank=True)
    stripe_connect_id = models.CharField(max_length=500, null=True, blank=True)
    client = models.ForeignKey(Client, null=True, related_name='client_onboarding', on_delete=models.SET_NULL)

    class Meta:
        verbose_name = "Onboarding"
        verbose_name_plural = "Onboardings"

    def __str__(self):
        return self.schema_name

onboarding/forms.py
from django import forms
from django.core.exceptions import ValidationError

from customers.models import Client
from onboarding.models import Onboarding


class OnboardingForm(forms.ModelForm):
    schema_name = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=50)
    contact_number = forms.CharField(max_length=15)

    class Meta:
        model = Onboarding
        fields = ('schema_name', 'email', 'contact_number', 'first_name', 'last_name')

    def clean_schema_name(self,):
        schema_name = self.cleaned_data['schema_name']
        if Onboarding.objects.filter(schema_name=schema_name).exists():
            raise ValidationError('schema name already taken.')
        return schema_name

onboarding/views.py
import secrets
import string
import time

import stripe
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.db import connection, IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render

# Create your views here.
from django.urls import reverse
from django.views.generic import TemplateView, FormView, ListView
from elasticsearch_dsl import Q
from tenant_schemas.utils import schema_context

from basket.models import BasketLine
from customers.email import SendEmail
from customers.models import Client
from dashboard.views import TenantIsActive
from onboarding.forms import OnboardingForm
from onboarding.godaddy.client import GoDaddyClientHelper
from onboarding.models import Plan, Onboarding
from products.documents import ProductDocument
from products.models import Products


class PlanListView(TenantIsActive, ListView):
    model = Products
    template_name = 'onboarding/plans.html'
    tenant_homepage = 'onboarding/tenant_home.html'
    context_object_name = 'products'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        plans = Plan.objects.filter(is_active=True).order_by('id')
        context = super().get_context_data(**kwargs)
        context['plans'] = plans
        context['tenant'] = connection.schema_name
        if connection.schema_name != 'public':
            with schema_context(connection.schema_name):
                context['basket_lines'] = BasketLine.objects.filter(basket_id=self.request.basket).count()
        return context

    def get_queryset(self):
        if connection.schema_name != 'public':
            return Products.objects.filter(is_available=True)
        return Plan.objects.filter(is_active=True).order_by('id')


    def get_template_names(self):
        if connection.schema_name == 'public':
            return self.template_name
        return self.tenant_homepage


class SearchView(TemplateView):
    template_name = 'onboarding/tenant_home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        q = self.request.GET.get('q')
        if q:
            response = ProductDocument().response(q)
            context['products'] = response
            context['searchterm'] = q
        elif self.request.GET.get('price'):
            price = int(self.request.GET.get('price'))
            response = ProductDocument().filter_by_price(price)
            context['products'] = response
        elif self.request.GET.get('category'):
            category = self.request.GET.get('category')
            response = ProductDocument().filter_by_category(category)
            context['products'] = response
        return context




class OnboardingFormView(FormView):
    template_name = 'onboarding/onboarding_form.html'
    form_class = OnboardingForm
    plan = None

    def form_valid(self, form):
        clientobj = form.save(commit=False)
        clientobj.domain_url = clientobj.schema_name + "." + settings.PUBLIC_DOMAIN_URL
        self.plan = Plan.objects.get(slug=self.kwargs.get('slug'))
        clientobj.plan = self.plan

        stripe.api_key = settings.STRIPE_SECRET_KEY
        if settings.IS_PRODUCTION:
            success_url = f"http://{settings.PUBLIC_DOMAIN_URL}/onboarding/success/"
        else:
            success_url = f"http://localhost:8000/onboarding/success/"
        session = stripe.checkout.Session.create(
            line_items=[
                {
                    "price_data": {
                        "currency": "gbp",
                        "product_data": {"name": self.plan.title},
                        "unit_amount": self.plan.price * 100,
                    },
                    "quantity": 1,
                },
            ],
            mode="payment",
            success_url=success_url + "{CHECKOUT_SESSION_ID}/",
            cancel_url="http://localhost:8000/cancel",
        )
        clientobj.session_id = session.id
        clientobj.save()
        return redirect(session.url)


class CreateOnboarding(TemplateView):
    template_name = "onboarding/payment_success.html"

    def get_context_data(self, **kwargs):
        onboarding = Onboarding.objects.get(session_id=self.kwargs.get('slug'))
        if onboarding.is_active is False:
            if settings.IS_PRODUCTION:
                godaddy = GoDaddyClientHelper()
                schema_name = onboarding.schema_name
                godaddy.add_cname_to_dns(schema_name)

            client = Client.objects.create(domain_url=onboarding.domain_url.lower(), schema_name=onboarding.schema_name.lower())
            onboarding.is_active = True
            onboarding.client = client
            onboarding.save()
            with schema_context(onboarding.schema_name):
                try:
                    user = User.objects.create(username='admin@setyour.shop')
                    characters = string.ascii_letters + string.digits
                    keyword = ''.join(secrets.choice(characters) for _ in range(8))
                    user.set_password(keyword)
                    user.is_superuser = True
                    user.is_staff = True
                    user.save()
                    site = Site.objects.first()
                    site.domain = onboarding.domain_url
                    site.save()
                    SendEmail().send_onboarded_admin_email(site.domain, keyword, onboarding.email)
                except IntegrityError as e:
                    pass
        context = super().get_context_data()
        context['website_url'] = onboarding.domain_url
        context['products'] = Products.objects.filter(is_available=True)
        context['schema_name'] = onboarding.schema_name

        return context

templates/onboarding/onboarding_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Plans</title>
</head>
<body>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<style>
  body {
    min-height: 100vh;
    background: url("https://images.unsplash.com/photo-1598125443421-779f98323fe4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80");
    background-repeat: no-repeat;
    background-size: cover;
    color: white;
    font-family: Roboto;
    font-size: 16px;
}
  .grid {
    display: grid;

    gap: 4%;
    padding: 12% 0;
}
label {
color:white;
font-weight: bold;
margin:5px;
}
button.cta_btn:hover {
    background: #000;
}

button.cta_btn {
    width: 100%;
    display: inline-block;
    text-align: center;
    background: rgba(21, 23, 24, 0.7);
    border-radius: 29px;
    margin-top:10px;
    padding: 20px 0;
    color: white;
    text-decoration: none;
    letter-spacing: 2px;
    transition: background .3s ease;
}
  .card {
    padding: 50px;
    background: rgba(255, 255, 255, 0.1);
    border: 2px solid rgba(255, 255, 255, 0.2);
    backdrop-filter: blur(10px);
    border-radius: 25px;
}
</style>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<section>
  <div class="container">

        <div class="grid">
          <div class="card">

      <form method="post" action="." novalidate autocomplete="off">
    {% csrf_token %}
          <label for="inputSchemaName">Schema Name</label>
      <input type="text" class="form-control" id="inputSchemaName" name="schema_name" placeholder="Enter your subdomain name" required>

        <div class="form-group">
      <label for="first_name">First Name</label>
      <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Enter your first name" required>
    </div>

        <div class="form-group">
      <label for="last_name">Last Name</label>
      <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Enter your last name" required>
    </div>

    <div class="form-group">
      <label for="inputEmail">Email</label>
      <input type="email" class="form-control" id="inputEmail" name="email" placeholder="Enter your email" required>
    </div>

    <div class="form-group">
      <label for="numericInput">Contact Number</label>
      <input type="text" class="form-control" id="numericInput" name="contact_number" pattern="[0-9]*" inputmode="numeric">
    </div>

    <button type="submit" class="cta_btn">Submit</button>
  </form>
  </div>
        </div>
  </div>
    {% include 'formerrors.html' %}
</section>
</body>

</html>

templates/onboarding/payment_success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Onboarding Success</title>
</head>
<body>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link href="{% static 'css/custom-style.css' %}" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap');

body {
    font-family: "Poppins", sans-serif;
    color: #444444;
}

a,
a:hover {
    text-decoration: none;
    color: inherit;
}

.section-products {
    padding: 80px 0 54px;
}

.section-products .header {
    margin-bottom: 50px;
}

.section-products .header h3 {
    font-size: 1rem;
    color: #fe302f;
    font-weight: 500;
}

.section-products .header h2 {
    font-size: 2.2rem;
    font-weight: 400;
    color: #444444;
}

.section-products .single-product {
    margin-bottom: 26px;
}

.section-products .single-product .part-1 {
    position: relative;
    height: 290px;
    max-height: 290px;
    margin-bottom: 20px;
    overflow: hidden;
}

.section-products .single-product .part-1::before {
		position: absolute;
		content: "";
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		z-index: -1;
		transition: all 0.3s;
}

.section-products .single-product:hover .part-1::before {
		transform: scale(1.2,1.2) rotate(5deg);
}



.section-products #product-2 .part-1::before {
    background: url("https://i.ibb.co/cLnZjnS/2.jpg") no-repeat center;
    background-size: cover;
}

.section-products #product-3 .part-1::before {
    background: url("https://i.ibb.co/L8Nrb7p/1.jpg") no-repeat center;
    background-size: cover;
}

.section-products #product-4 .part-1::before {
    background: url("https://i.ibb.co/cLnZjnS/2.jpg") no-repeat center;
    background-size: cover;
}

.section-products .single-product .part-1 .discount,
.section-products .single-product .part-1 .new {
    position: absolute;
    top: 15px;
    left: 20px;
    color: #ffffff;
    background-color: #fe302f;
    padding: 2px 8px;
    text-transform: uppercase;
    font-size: 0.85rem;
}

.section-products .single-product .part-1 .new {
    left: 0;
    background-color: #444444;
}

.section-products .single-product .part-1 ul {
    position: absolute;
    bottom: -41px;
    left: 20px;
    margin: 0;
    padding: 0;
    list-style: none;
    opacity: 0;
    transition: bottom 0.5s, opacity 0.5s;
}

.section-products .single-product:hover .part-1 ul {
    bottom: 30px;
    opacity: 1;
}

.section-products .single-product .part-1 ul li {
    display: inline-block;
    margin-right: 4px;
}

.section-products .single-product .part-1 ul li a {
    display: inline-block;
    width: 40px;
    height: 40px;
    line-height: 40px;
    background-color: #ffffff;
    color: #444444;
    text-align: center;
    box-shadow: 0 2px 20px rgb(50 50 50 / 10%);
    transition: color 0.2s;
}

.section-products .single-product .part-1 ul li a:hover {
    color: #fe302f;
}

.section-products .single-product .part-2 .product-title {
    font-size: 1rem;
}

.section-products .single-product .part-2 h4 {
    display: inline-block;
    font-size: 1rem;
}

.section-products .single-product .part-2 .product-old-price {
    position: relative;
    padding: 0 7px;
    margin-right: 2px;
    opacity: 0.6;
}

.section-products .single-product .part-2 .product-old-price::after {
    position: absolute;
    content: "";
    top: 50%;
    left: 0;
    width: 100%;
    height: 1px;
    background-color: #444444;
    transform: translateY(-50%);
}
</style>
<section>
        <div class="container py-5">

            <h3>We are setting up your website you can access your website at: <a style="color:blue" href="http://{{website_url}}">{{website_url}}</a></h3>
        </div>
</section>
<section class="section-products">
		<div class="container">
				<div class="row justify-content-center text-center">
						<div class="col-md-8 col-lg-6">
								<div class="header">
										<h3>Popular Products you can add to your website</h3>
								</div>
						</div>
				</div>
				<div class="row">
						<!-- Single Product -->
                    {% for product in products %}
						<div class="col-md-6 col-lg-4 col-xl-3">
								<div id="product-1" class="single-product">
										<div class="part-1" style="background: url('{{product.get_image_url}}') no-repeat center/cover ">
												<ul>

														<li class="add-to-website"  name="{{product.title}}" id="{{product.id}}"><a href="#"><i class="fas fa-plus"></i></a></li>

												</ul>
										</div>
										<div class="part-2">
												<h3 class="product-title">{{product.title}}</h3>
												<h4 class="product-price">£{{product.price}}</h4>
										</div>
								</div>
						</div>
                    {% endfor %}
						<!-- Single Product -->
				</div>
		</div>
</section>


</body>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
<script>
	 toastr.options = {
  "closeButton": false,
  "debug": false,
  "newestOnTop": false,
  "progressBar": true,
  "positionClass": "toast-bottom-center",
  "preventDuplicates": false,
  "onclick": null,
  "showDuration": "300",
  "hideDuration": "1000",
  "timeOut": "1000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut"
}
	$(".add-to-website").on("click", function(event) {
	event.preventDefault();
	data = {"id": $(this).attr("id"), "schema_name": "{{schema_name}}"};
	let name = $(this).attr("name");
    $.ajax({
                url: "{% url 'products:add_product' %}", // Replace with your API endpoint
                method: "POST",
                dataType: "json",
                data: data,
                success: function(response) {
                toastr.success(name+" added to your website")
                },
                error: function(xhr, status, error) {
                    // Handle error
                    toastr.error("cannot add "+name+" to your website")
                    console.error("AJAX Request Error:", status, error);
                }
            });
});
</script>
</html>

templates/onboarding/plans.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home:Plans</title>
    <!-- Add your CSS styles or link to an external stylesheet here -->
    <style>
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    min-height: 100vh;
    background: url("https://images.unsplash.com/photo-1598125443421-779f98323fe4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80");
    background-repeat: no-repeat;
    background-size: cover;
    color: white;
    font-family: Roboto;
    font-size: 16px;
}

.container {
    max-width: 1320px;
    margin: 0 auto;
    padding: 0 2rem;
    height: 100%;
}

.grid {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    gap: 4%;
    padding: 12% 0;
}

.card {
    padding: 50px;
    background: rgba(255, 255, 255, 0.1);
    border: 2px solid rgba(255, 255, 255, 0.2);
    backdrop-filter: blur(10px);
    border-radius: 25px;
}

.card_title {
    font-weight: normal;
    font-size: 36px;
    margin-bottom: 20px;
}

.pricing {
    font-weight: normal;
    font-size: 96px;
}

.pricing .small {
    font-size: 16px;
}

hr {
    margin-top: 70px;
}

.features {
    margin: 40px 0;
    list-style-position: inside;
}

.features li {
    padding-bottom: 10px;
}

a.cta_btn {
    width: 100%;
    display: inline-block;
    text-align: center;
    background: rgba(21, 23, 24, 0.7);
    border-radius: 29px;
    padding: 20px 0;
    color: white;
    text-decoration: none;
    letter-spacing: 2px;
    transition: background .3s ease;
}

a.cta_btn:hover {
    background: #000;
}
.link {
    position: fixed;
    background-color: #D12322;
    padding: 23px 40px;
    right: -99px;
    border-radius: 5px;
    top: 50%;
    transform: translateY(-50%);
    transform: rotate(-90deg);
    font-size: 18px;
    font-weight: 500;
    color: #FFF;
    text-decoration: none;
    text-transform: capitalize;
    transition: all .1s ease-in-out;
}

.link i {
    padding-left: 7px;
}

.link:hover {
    text-decoration: underline;
    background-color: black;
}
@media only screen and (max-width: 1024px) {
    .grid {
        grid-template-columns: 1fr 1fr;
        gap: 2%;

    }
}

@media only screen and (max-width: 425px) {
    .grid {
        grid-template-columns: 1fr;
        gap: 2%;
        padding-bottom: 25%;
    }

    .container {
        padding: 0 1rem;
    }

    body {
        font-size: 14px;
    }

    .card {
        padding: 30px;
    }

    .card_title {
        font-size: 24px;
        margin-bottom: 12px;
    }

    .pricing {
        font-size: 52px;
    }

    hr {
        margin-top: 50px;
    }

    a.cta_btn {
        font-size: 11px;
    }
}
</style>
</head>
<body>

    <div class="container">
        <div class="grid">
            {% for plan in plans %}
                <div class="card">
                    <h2 class="card_title plan_title">{{plan.title}}</h2>
                    <p class="pricing">£{{plan.price}}<span class="small">/per month</span></p>
                    <hr>
                    <ul class="features">
                        {% for feature in plan.decription_array %}
                            <li>{{feature}}</li>
                        {% endfor %}
                    </ul>
                    <a href="{% url 'onboarding' slug=plan.slug %}" class="cta_btn">Buy Now</a>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- Add your JavaScript scripts or link to external scripts here -->

</body>
</html>

templates/onboarding/tenant_home.html
{% extends 'base.html' %}
{% load helpertags %}
{% block body %}


<div class="container">

    <section class="section-products">
        <div class="container">
            <div class="row justify-content-center text-center">
            </div>
            <div class="row">
                <!-- Single Product -->
                {% for product in products %}
                <div class="col-md-6 col-lg-4 col-xl-3">
                    <div id="product-1" class="single-product">
                        <div class="part-1"
                             style="background: url('{{product.get_image_url}}') no-repeat center/cover ">
                            <ul>

                                <li  class="add-to-cart {% check_product_exists request.basket product.id as exists %}{% if exists %}d-none{% endif %}" id="{{product.id}}"><a href="#">
                                    <i class="fa-solid fa-cart-plus"></i>
                                </a></li>
                            </ul>

                        </div>
                        <div class="basket_details b_d_{{product.id}} "{% if exists %} style="opacity:1" {% endif %}>
                        <button class="btn btn-danger btn-minus" product_id="{{product.id}}" input_id="#count_{{product.id}}" style="width:30px;">-</button>
                        <input  type="text" id="count_{{product.id}}" {% if exists%}value="{% get_product_count request.basket product %}{% endif %}" style="width:30px; text-align:center; font-weight:bold;">
                        <button class="btn btn-success btn-plus" product_id="{{product.id}}" input_id="#count_{{product.id}}" style="width:30px;">+</button>
                            </div>
                        <div class="part-2">
                            <h3 class="product-title">{{product.title}}</h3>
                            <h4 class="product-price">£{{product.price}}</h4>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <!-- Single Product -->
            </div>
        </div>
    </section>
        </div>
<div class="pagination text-center" style="margin-left:550px">
    <span class="step-links" style="color:white">
        {% if page_obj.has_previous %}
            <a href="?page=1" style="color:white">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}" style="color:white">previous</a>
        {% endif %}

<!--        <span class="current">-->
<!--            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.-->
<!--        </span>-->

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" style="color:white">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" style="color:white">last &raquo;</a>
        {% endif %}
    </span>
</div>


<script>
    toastr.options = {
  "closeButton": false,
  "debug": false,
  "newestOnTop": false,
  "progressBar": true,
  "positionClass": "toast-bottom-center",
  "preventDuplicates": false,
  "onclick": null,
  "showDuration": "300",
  "hideDuration": "1000",
  "timeOut": "1000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut"
}
    $(".add-to-cart").on("click", function(e) {
        e.preventDefault();
        $(".b_d_"+$(this).attr("id")).css("opacity", 1);
        $(".b_d_"+$(this).attr("id")).show();
        $(this).hide();
        var count_element = $("#count_"+$(this).attr("id"));
        data = {"id": $(this).attr("id"), "quantity": 1};
        addToBasket(data,count_element, "add");
    });

    function addToBasket(data, count_element, action) {
    $.ajax({
        url: "{% url 'basket:add_to_basket' %}",
        method: "POST",
        dataType: "json",
        data: data,
        success: function(response) {
            $('.badge-notification').text(response.count);
            count_element.val(response.product_count);
            if((response.product_count == 1) && action == "add"){
                toastr.success('Product added to basket');
            }
        },
        error: function(xhr, status, error) {
            // Handle error
            toastr.error(xhr.responseJSON.message);
            count_element.val(xhr.responseJSON.product_count);
            console.error("AJAX Request Error:", status, error);
        }
    });
}

    $(".btn-minus").on("click", function(e) {
        e.preventDefault();
        var element = $(this);
        var decrement_value = parseInt($(element.attr("input_id")).val());
        var count_element = $(element.attr("input_id"));
        if(decrement_value > 1){
            $(element.attr("input_id")).val(decrement_value - 1);
            data = {"id": element.attr("product_id"), "quantity": decrement_value - 1};
            addToBasket(data,count_element, "remove");

        }
        else if(decrement_value == 1){
            $(this).parent().hide();
            $("#"+element.attr("product_id")).show();
            $("#"+element.attr("product_id")).removeClass("d-none");
            data = {"id": element.attr("product_id"), "quantity": 0};
            addToBasket(data,count_element, "add");
        }

    });

    $(".btn-plus").on("click", function(e) {
        e.preventDefault();
        var element = $(this);
        var count_element = $(element.attr("input_id"));
        var increment_value = parseInt($(element.attr("input_id")).val());
        $(element.attr("input_id")).val(parseInt(increment_value) + 1);
        data = {"id": element.attr("product_id"), "quantity": increment_value + 1};
        addToBasket(data,count_element);

    });
</script>
{% endblock %}