basket/urls.py
from django.urls import path
from django.views.generic import TemplateView

from basket.views import AddToBasket, BasketDetailView, stripe_basket_checkout, SuccessView

app_name = 'basket'

urlpatterns = [
    path('add-to-basket', AddToBasket.as_view(), name="add_to_basket"),
    path('view-basket', BasketDetailView.as_view(), name="view_basket"),
    path('checkout-basket', stripe_basket_checkout, name="checkout_basket"),
    path('payment-error', TemplateView.as_view(template_name='basket/payment-error.html'), name="payment_error"),
    path('payment-success/<slug:slug>/', SuccessView.as_view(), name="payment_success"),
]

cms/urls.py
from django.urls import path

from cms.views import BlogListView, BlogDetailView

app_name = 'basket'

urlpatterns = [
path('', BlogListView.as_view(), name='blog_list'),
path('<int:pk>/', BlogDetailView.as_view(), name='blog_details'),
]

customers/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from customers.views import CustomerLogin, RegisterCustomer, AddAddress

app_name = "customers"

urlpatterns = [
    path('login/', CustomerLogin.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterCustomer.as_view(), name="register"),
    path('add-address/', AddAddress.as_view(), name="add_address"),
]

goshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from onboarding.views import PlanListView, OnboardingFormView, CreateOnboarding, SearchView


schema_view = get_schema_view(
    openapi.Info(
        title="Shopping API",
        default_version="v2",
        description="This Document has all the API endpoints for building setyour shop web pages.",
        terms_of_service="https://www.setyour.shop",
        contact=openapi.Contact(email="mohammed.sagheer95@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', SearchView.as_view(), name='search'),

    path('', PlanListView.as_view(), name='plans'),
    path("customer/", include('customers.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('onboarding/', include('onboarding.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('api/', include('restapis.urls')),
path(
            "swagger/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
    path('blogs/', include('cms.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls'))

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load helpertags %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>Home:Products</title>
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <link href="{% static 'css/custom-style.css' %}" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap');

    body {
        font-family: "Poppins", sans-serif;
        color: #444444;
    }

    a,
    a:hover {
        text-decoration: none;
        color: inherit;
    }

    .section-products {
        padding: 80px 0 54px;
    }

    .section-products .header {
        margin-bottom: 50px;
    }

    .section-products .header h3 {
        font-size: 1rem;
        color: #fe302f;
        font-weight: 500;
    }

    .section-products .header h2 {
        font-size: 2.2rem;
        font-weight: 400;
        color: #444444;
    }

    .section-products .single-product {
        margin-bottom: 26px;
    }

    .section-products .single-product .part-1 {
        position: relative;
        height: 290px;
        max-height: 290px;
        margin-bottom: 20px;
        overflow: hidden;
    }

    .section-products .single-product .part-1::before {
            position: absolute;
            content: "";
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
            transition: all 0.3s;
    }

    .section-products .single-product:hover .part-1::before {
            transform: scale(1.2,1.2) rotate(5deg);
    }



    .section-products #product-2 .part-1::before {
        background: url("https://i.ibb.co/cLnZjnS/2.jpg") no-repeat center;
        background-size: cover;
    }

    .section-products #product-3 .part-1::before {
        background: url("https://i.ibb.co/L8Nrb7p/1.jpg") no-repeat center;
        background-size: cover;
    }

    .section-products #product-4 .part-1::before {
        background: url("https://i.ibb.co/cLnZjnS/2.jpg") no-repeat center;
        background-size: cover;
    }

    .section-products .single-product .part-1 .discount,
    .section-products .single-product .part-1 .new {
        position: absolute;
        top: 15px;
        left: 20px;
        color: #ffffff;
        background-color: #fe302f;
        padding: 2px 8px;
        text-transform: uppercase;
        font-size: 0.85rem;
    }

    .section-products .single-product .part-1 .new {
        left: 0;
        background-color: #444444;
    }

    .section-products .single-product .part-1 ul {
        position: absolute;
        bottom: -41px;
        left: 20px;
        margin: 0;
        padding: 0;
        list-style: none;
        opacity: 0;
        transition: bottom 0.5s, opacity 0.5s;
    }

    .section-products .single-product .basket_details {
        position: absolute;
        bottom: 120px;
        left: 60px;
        margin: 0;
        padding: 0;
        list-style: none;
        opacity: 0;
        transition: bottom 0.5s, opacity 0.5s;
    }

    .section-products .single-product:hover .part-1 ul {
        bottom: 30px;
        opacity: 1;
    }

    .section-products .single-product .part-1 ul li {
        display: inline-block;
        margin-right: 4px;
    }

    .section-products .single-product .part-1 ul li a {
        display: inline-block;
        width: 40px;
        height: 40px;
        line-height: 40px;
        background-color: #ffffff;
        color: #444444;
        text-align: center;
        box-shadow: 0 2px 20px rgb(50 50 50 / 10%);
        transition: color 0.2s;
    }

    .section-products .single-product .part-1 ul li a:hover {
        color: green;
    }

    .section-products .single-product .part-2 .product-title {
        font-size: 1rem;
        color: white;
    }
    .product-price{
        color: white;
    }

    .section-products .single-product .part-2 h4 {
        display: inline-block;
        font-size: 1rem;
    }

    .section-products .single-product .part-2 .product-old-price {
        position: relative;
        padding: 0 7px;
        margin-right: 2px;
        opacity: 0.6;
    }

    .section-products .single-product .part-2 .product-old-price::after {
        position: absolute;
        content: "";
        top: 50%;
        left: 0;
        width: 100%;
        height: 1px;
        background-color: #444444;
        transform: translateY(-50%);
    }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">{{request.tenant.domain_url}}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <a style="color:white" class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
    {% if request.tenant.can_publish_cms %}
    <a style="color:white" class="nav-link" href="/blogs">Blogs <span class="sr-only">(current)</span></a>
    {% endif %}
    <form class="form-inline my-2 my-lg-0" method="get" action="{% if request.resolver_match.url_name == 'blog_list' %}{% else %}/search/{% endif %}" autocomplete="off">
      <input {%if searchterm %}value="{{searchterm}}"{% endif %} class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
    </form>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Filter by price
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/search?price=50">upto £50</a>
          <a class="dropdown-item" href="/search?price=100">£50 - £100</a>
          <a class="dropdown-item" href="/search?price=150">£100 - £150</a>
          <a class="dropdown-item" href="/search?price=200">£150 - £200</a>
        </div>
      </li>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Filter by Category
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% get_categories as categories %}
            {% for category in categories %}
          <a class="dropdown-item" href="/search?category={{category.title}}">{{category.title}}</a>
            {% endfor %}
        </div>
      </li>
    </ul>


      <ul class="navbar-nav">
    <li class="nav-item">
  <a href="{% url 'basket:view_basket' %}" style="color:white" class="nav-link">
    <i class="fa-solid fa-cart-shopping {{request.basket}}"></i> Cart
    <span class="badge rounded-pill badge-notification bg-danger">{{basket_lines}}</span>
  </a>
</li>

              {% if request.user.is_authenticated %}
        <li class="nav-item"><a  class="nav-link" href="{% url 'customers:logout' %}" style="color:white"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        {% else %}
      <li class="nav-item"><a  class="nav-link" href="{% url 'customers:login' %}" style="color:white"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% endif %}

      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}

{% block script %}
{% endblock %}

</body>
</html>

templates/formerrors.html
{% if form.errors %}
  <ul class="errorlist">
    {% for field_name, field_errors in form.errors.items %}
      {% for error in field_errors %}
        <li>
          <div class="alert alert-danger" role="alert">
            {{ field_name }}: {{ error }}
          </div>
        </li>
      {% endfor %}
    {% endfor %}
  </ul>
{% endif %}