basket/urls.py
from django.urls import path
from django.views.generic import TemplateView

from basket.views import AddToBasket, BasketDetailView, stripe_basket_checkout, SuccessView

app_name = 'basket'

urlpatterns = [
    path('add-to-basket', AddToBasket.as_view(), name="add_to_basket"),
    path('view-basket', BasketDetailView.as_view(), name="view_basket"),
    path('checkout-basket', stripe_basket_checkout, name="checkout_basket"),
    path('payment-error', TemplateView.as_view(template_name='basket/payment-error.html'), name="payment_error"),
    path('payment-success/<slug:slug>/', SuccessView.as_view(), name="payment_success"),
]

cms/urls.py
from django.urls import path

from cms.views import BlogListView, BlogDetailView

app_name = 'basket'

urlpatterns = [
path('', BlogListView.as_view(), name='blog_list'),
path('<int:pk>/', BlogDetailView.as_view(), name='blog_details'),
]

customers/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from customers.views import CustomerLogin, RegisterCustomer, AddAddress

app_name = "customers"

urlpatterns = [
    path('login/', CustomerLogin.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterCustomer.as_view(), name="register"),
    path('add-address/', AddAddress.as_view(), name="add_address"),
]

goshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from onboarding.views import PlanListView, OnboardingFormView, CreateOnboarding, SearchView


schema_view = get_schema_view(
    openapi.Info(
        title="Shopping API",
        default_version="v2",
        description="This Document has all the API endpoints for building setyour shop web pages.",
        terms_of_service="https://www.setyour.shop",
        contact=openapi.Contact(email="mohammed.sagheer95@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', SearchView.as_view(), name='search'),

    path('', PlanListView.as_view(), name='plans'),
    path("customer/", include('customers.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('onboarding/', include('onboarding.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('api/', include('restapis.urls')),
path(
            "swagger/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
    path('blogs/', include('cms.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls'))

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/models.py
from django.contrib.auth.models import User
from django.db import models

from customers.abstract_model import TimeStamp
from products.models import Products


# Create your models here.

class Basket(TimeStamp):
    OPEN, SUBMITTED, MERGED = ("Open", "Submitted", "Merged")
    STATUS = (
        (OPEN, "Open - currently active"),
        (SUBMITTED, "Submitted - has been ordered at the checkout"),
        (MERGED, "Merged - has been merged with old basket"),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(choices=STATUS, default=OPEN, max_length=100)
    submitted_at = models.DateTimeField(null=True)

    def __str__(self):
        return str(self.id)

    def total(self):
        sum = 0
        for line in self.lines.all():
            sum += line.price * line.quantity
        return sum
    @classmethod
    def create_basket(self, user):
        if user.is_authenticated:
            basket = Basket.objects.create(user=user)
            return basket
        basket  = Basket.objects.create()
        return basket

    @classmethod
    def get_basket(self, user):
        if not user.basket_set.exists():
            return self.create_basket(user)
        basket = user.basket_set.last()
        if basket.status == basket.OPEN:
            return basket
        else:
            return self.create_basket(user)

    def create_basket_lines(self, product_id, quantity):
        product = Products.objects.get(id=product_id)
        if int(quantity) == 0:
            self.lines.filter(product_id=product_id).delete()
        elif self.lines.filter(product_id=product_id).exists():
            price = int(quantity) * product.price
            self.lines.filter(product_id=product_id).update(quantity=int(quantity), price=price)
        else:
            line = BasketLine.objects.create(basket=self, product_id=product_id, quantity=int(quantity),
                                             price=product.price)
        return self.lines.count()

    def merge_basket_lines(self, product_id, quantity):
        product = Products.objects.get(id=product_id)
        if int(quantity) == 0:
            self.lines.filter(product_id=product_id).delete()
        elif self.lines.filter(product_id=product_id).exists():
            orginal_quantity = self.lines.filter(product_id=product_id).first().quantity
            quantity += orginal_quantity
            price = int(quantity) * product.price
            self.lines.filter(product_id=product_id).update(quantity=int(quantity), price=price)
        else:
            line = BasketLine.objects.create(basket=self, product_id=product_id, quantity=int(quantity),
                                             price=product.price)
        return self.lines.count()

    @classmethod
    def merge_basket(cls, old_basket_id, new_basket_id):
        if old_basket_id != new_basket_id:
            old_basket = Basket.objects.get(id=old_basket_id)
            new_basket = Basket.objects.get(id=new_basket_id)
            if old_basket.status != Basket.MERGED:
                for line in old_basket.lines.all():
                    new_basket.merge_basket_lines(line.product_id, line.quantity)
                old_basket.status = Basket.MERGED
                old_basket.save()

    def get_product_line_count(self, product_id):
        if self.lines.filter(product_id=product_id).exists():
            return self.lines.filter(product_id=product_id).first().quantity
        return 0


class BasketLine(TimeStamp):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE, related_name="lines")
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name="products")
    quantity = models.IntegerField()
    price = models.FloatField()

    class Meta:
        verbose_name = "Line"
        verbose_name_plural = "Lines"

    def __str__(self):
        return f"{self.product.__str__()}-{self.quantity}"

basket/views.py
import stripe
from django.conf import settings
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils import timezone
from django.views import View
from django.views.generic import DetailView, TemplateView
from tenant_schemas.utils import schema_context

from basket.models import Basket
from onboarding.models import Onboarding
from orders.models import Order
from products.models import Products


# Create your views here.


class AddToBasket(View):

    def post(self, request):
        data = request.POST
        basket = Basket.objects.get(id=request.basket)
        product_id = data.get('id')
        try:
            product_count = basket.get_product_line_count(product_id)
            if int(data.get('quantity')) > Products.objects.get(id=product_id).stock:
                return JsonResponse({"message": "Cannot add to cart low stock", "product_count": product_count}, status=400)
        except Exception as e:
            print(str(e))
        lines = basket.create_basket_lines(product_id, data.get('quantity'))
        product_count = basket.get_product_line_count(product_id)
        return JsonResponse({"message": "Added to Cart", "count": lines, "product_count": product_count})


class BasketDetailView(DetailView):
    model = Basket
    template_name = 'basket/basket.html'

    def get_object(self, queryset=None):
        return Basket.objects.get(id=self.request.basket)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lines_exists'] = self.get_object().lines.exists()
        if self.request.user.is_authenticated:
            context['addresses'] = self.request.user.shipping_address.all()
        return context



def stripe_basket_checkout(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/customer/login?next=/basket/view-basket')
    stripe.api_key = settings.STRIPE_SECRET_KEY
    line_items = []
    request.session["address_id"] = request.POST.get("selected_shipping_address")
    basket = Basket.objects.get(id=request.basket)
    for line in  basket.lines.all():
        price_data = {"product_data": {"name": line.product.title}, "currency": "gbp", "unit_amount": line.product.price * 100}
        line_object = {"price_data": price_data, "quantity": line.quantity}
        line_items.append(line_object)
    stripe_account = ''
    schema_name = request.tenant.schema_name
    with schema_context('public'):
        stripe_account = Onboarding.objects.get(schema_name=schema_name).stripe_connect_id
    success_url = f"https://{request.tenant.domain_url}/basket/payment-success/"
    cancel_url = f"https://{request.tenant.domain_url}/basket/payment-error/"
    session = stripe.checkout.Session.create(line_items=line_items,mode="payment",
                                             success_url=success_url + "{CHECKOUT_SESSION_ID}/",
                                             cancel_url=cancel_url,
                                             stripe_account=stripe_account
                                             )
    return HttpResponseRedirect(session.url)


class SuccessView(LoginRequiredMixin, TemplateView):
    template_name = 'basket/success.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        stripe.api_key = settings.STRIPE_SECRET_KEY
        try:
            schema_name = self.request.tenant.schema_name
            with schema_context('public'):
                stripe_account = Onboarding.objects.get(schema_name=schema_name).stripe_connect_id
            session = stripe.checkout.Session.retrieve(id=kwargs.get('slug'), stripe_account=stripe_account)
            order_created = False
            if Order.objects.filter(transaction_id=session.id).exists():
                order = Order.objects.filter(transaction_id=session.id).first()
                context['order'] = order
                order_created = True
                context['status'] = "Success"
            if session.status == "complete" and not order_created:
                context['status'] = "Success"
                basket = Basket.objects.get(id=self.request.basket)
                basket.status = basket.SUBMITTED
                basket.submitted_at = timezone.now()
                basket.save()
                number = settings.ORDER_NUMBERING_FROM + basket.id
                shipping_address = self.request.session.get("address_id")
                order = Order.objects.create(basket=basket, user=basket.user, number=str(number),
                                     total_incl_tax=session.amount_total/100, transaction_id=session.id,
                                     shipping_address_id=shipping_address)
                context['order'] = order
        except Exception as e:
            context['status'] = "Error"
        return context

templates/basket/basket.html
{% extends 'base.html' %}



    {% block title %}
    <title>Basket</title>
    {% endblock %}

{% block body %}
<style>
    .shadow {
  box-shadow: 5px 5px 2px 6px lightblue;
}

    .wd-25{
    width:25%
    }
</style>
<div class="container my-5" style="background-color: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
    <h2 class="text-center mb-4">Shopping Cart</h2>

    {% for line in view.object.lines.all %}
        <div class="card mb-3 shadow" style="height: 150px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{line.product.get_image_url}}" class="img-thumbnail" alt="{{line.product.title}}" style="width: 100px; height: 100px;">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{line.product.title}}</h5>
                        <p class="card-text">£{{line.price}}</p>
                        <p class="card-text"><small class="text-muted">Quantity: {{line.quantity}}</small></p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    <!-- Basket Total Div -->
    <div class="basket-total text-white bg-dark p-3 " style="border-radius: 10px;">
        {% if request.user.is_authenticated %}
        <h1>Shipping Address</h1>
       {% for address in addresses %}
    <div class="form-check">
        <input class="form-check-input selectedAddress" type="radio" name="selectedAddress" id="address{{ address.id }}" value="{{ address.id }}">
        <label class="form-check-label" for="address{{ address.id }}">
            {{ address.full_address }}
        </label>
    </div>
{% endfor %}
<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header bg-dark" id="headingThree">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#addAddressCollapse" aria-expanded="false" aria-controls="addAddressCollapse">
          Add Shipping Address
        </button>
      </h2>
    </div>

    <div id="addAddressCollapse" class="collapse bg-dark" aria-labelledby="headingThree" data-parent="#accordionExample">

        <form id="add-address" action="{% url 'customers:add_address' %}" method="post">
            <div class="form-outline mb-4 wd-25">
                <input type="text" id="line_1" name="line_1" class="form-control form-control-sm"/>
                <label class="form-label" for="line_1">Line 1</label>
            </div>
            <div class="form-outline mb-4 wd-25">
                <input type="text" id="line_2" name="line_2" class="form-control form-control-sm"/>
                <label class="form-label" for="line_2">Line 2</label>
            </div>
            <div class="form-outline mb-4 wd-25">
                <input type="text" id="city" name="city" maxlength="20" class="form-control form-control-sm"/>
                <label class="form-label" for="city" >City</label>
            </div>
            <div class="form-outline mb-4 wd-25">
                <input type="text" id="postcode" name="postcode" maxlength="8" class="form-control form-control-sm"/>
                <label class="form-label" for="postcode" >PostCode</label>
            </div>
            <div class="form-outline mb-4 wd-25">
                <input type="checkbox" id="is_default" name="is_default" class="form-control form-control-sm"/>
                <label class="form-label" for="is_default" >Is Default</label>
            </div>
            <input type="submit" value="submit" class="btn btn-danger">
        </form>

    </div>
  </div>
</div>

        {% endif %}
        <h4 class="mb-3">Basket Total</h4>
        <p>Total: £{{ view.object.total }}</p>
        {% if lines_exists %}
    <form method="post" action="{% url 'basket:checkout_basket' %}" id="checkoutForm">
        {% csrf_token %}
        <input id="selected_shipping_address" name="selected_shipping_address" {% if request.user.is_authenticated %}value=""{% else %}value="0"{% endif %} type="hidden">
        <button id="checkoutBasketButton" type="submit" class="btn btn-primary checkout-basket" >Checkout</button>
    </form>
{% endif %}
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $("#add-address").on("submit", function(e){
    e.preventDefault();
    var addressData = new FormData($(this)[0]);

    $.ajax({
        url: "{% url 'customers:add_address' %}",
        method: "POST",
        dataType: "json",
        data: addressData,
        contentType: false,
        processData: false,
            success: function(response) {
                toastr.success('Address for shipping has been added.');
                location.reload();
            },
            error: function(xhr, status, error) {
                // Handle errors
                console.error(xhr.responseText);
            }
        });
    });

    $("#checkoutBasketButton").on("click", function(e){
        e.preventDefault();
        if($("#selected_shipping_address").val() == ""){
            toastr.error("Add or select an Address")
            return false;
        }
        else {
           $("#checkoutForm").submit();
        }
    })

    $(".selectedAddress").on("click", function(e){
        $("#selected_shipping_address").val($(this).val());
        $("#checkoutBasketButton").prop("disabled", false);

    })

</script>
{% endblock %}

templates/basket/payment-error.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    <title>Payment Error</title>
{% endblock %}

{% block body %}
<style>
    .shadow {
        box-shadow: 5px 5px 2px 6px lightblue;
    }
</style>
<div class="container my-5" style="background-color: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
    <h2 class="text-center mb-4">Payment Error</h2>

    <div class="payment-error-message bg-white mb-4 p-4">
        <p>{% trans "Oops! There was an error processing your payment. Please try again later." %}</p>
    </div>

    <div class="back-to-home text-center">
        <a href="/" class="btn btn-primary"><i class="fa fa-home pr-2"></i>{% trans 'Back to Home' %}</a>
    </div>
</div>
{% endblock %}

templates/basket/success.html
{% extends 'base.html' %}
{% load i18n %}



    {% block title %}
    <title>Basket</title>
    {% endblock %}

{% block body %}
<style>
    .shadow {
  box-shadow: 5px 5px 2px 6px lightblue;
}
</style>
<div class="container my-5" style="background-color: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
    <h2 class="text-center mb-4">Payment {{status}}</h2>
<div class="shopping-cart-area  pt-80 pb-80">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="shopping-cart">
                    <div class="order-received mb-2">
                        <a href="/" class="btn btn-back"><i class="fa fa-angle-left pr-2"></i>{% trans 'Back' %}</a>
                    </div>
                    <!-- Tab panes -->
                    <div class="tab-content">

                        <!-- order-complete start -->
                        <div class="tab-pane active" id="order-complete">
                            <form action="#">
                                <div class="thank-recieve bg-white mb-30">
                                    <p>{% trans "Thank you. Your order has been received." %}</p>
                                </div>
                                <div class="order-info bg-white text-center clearfix mb-30">
                                    <div class="single-order-info">
                                        <h5 class="text-uppercase">{% trans "order no" %}</h5>
                                        <p class="text-uppercase text-light-black mb-0"><strong>{{ order.number }}</strong></p>
                                    </div>
                                    <div class="single-order-info">
                                        <h5 class="text-uppercase">{% trans "Date" %}</h5>
                                        <p class="text-uppercase text-light-black mb-0"><strong>{{ order.created_at|date:'d/m/Y' }}</strong></p>
                                    </div>
                                    <div class="single-order-info">
                                        <h5 class="text-uppercase">{% trans "Total" %}</h5>
                                        <p class="text-uppercase text-light-black mb-0"><strong>GBP  {{ order.total_incl_tax }}</strong></p>
                                    </div>
                                    <div class="single-order-info">
                                        <h5 class="text-uppercase">{% trans "payment method" %}</h5>
                                        <p class="text-uppercase text-light-black mb-0"><strong>{% if order.transaction_id %}ONLINE{% else %}CASH ON DELIVERY{% endif %}</strong></p>
                                    </div>

                                    <div class="single-order-info">
                                        <h5 class="text-uppercase">{% trans "Shipping address" %}</h5>
                                        <p class="text-uppercase text-light-black mb-0"><strong>{{order.shipping_address.full_address}}</strong></p>
                                    </div>
                                </div>
                                <div class="shop-cart-table check-out-wrap">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="our-order payment-details pr-20">
                                                <h4 class="title-1 title-border text-uppercase mb-30">{% trans "your order" %}</h4>
                                                <table>
                                                    <thead>
                                                        <tr>
                                                            <th><strong>{% trans "Product" %}</strong></th>
                                                            <th class="text-end"><strong>{% trans "Total" %}</strong></th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        {% for line in order.basket.lines.all %}
                                                        <tr>
                                                            <td>{{ line.product.title }} x {{ line.quantity }}</td>
                                                            <td class="text-end">GBP {{ line.price }}</td>
                                                            <td><img src="{{line.product.get_image_url}}" height="150" width="100"></td>
                                                        </tr>
                                                        {% endfor %}
                                                        <tr>
                                                            <td>{% trans "Cart Subtotal" %}</td>
                                                            <td class="text-end">GBP {{ order.total_incl_tax }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td>{% trans "Order Total" %}</td>
                                                            <td class="text-end">GBP {{ order.total_incl_tax }}</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- order-complete end -->

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}