cms/urls.py
from django.urls import path

from cms.views import BlogListView, BlogDetailView

app_name = 'basket'

urlpatterns = [
path('', BlogListView.as_view(), name='blog_list'),
path('<int:pk>/', BlogDetailView.as_view(), name='blog_details'),
]

customers/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from customers.views import CustomerLogin, RegisterCustomer, AddAddress

app_name = "customers"

urlpatterns = [
    path('login/', CustomerLogin.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterCustomer.as_view(), name="register"),
    path('add-address/', AddAddress.as_view(), name="add_address"),
]

dashboard/urls.py
from django.urls import path

from dashboard.views import DashboardHomeView, DashboardLogin, OrderListView, PublicSchemaProductImport, \
    StoreProductListView, OrderEditView, ChangeProductStatus, CreateProductView, BrandsListView, AddBrandView, \
    EditBrandView, CategoryListView, AddCategoryView, EditCategoryView, EditProductView, BlogsListView, AddBlogsView, \
    EditBlog, OnboardingListView, OnboardingEditView, ChangeStatus, DeleteBrand, DeleteCategory

app_name = 'dashboard'

urlpatterns = [
    path('', DashboardHomeView.as_view(), name='dashboard_home'),
    path('login/', DashboardLogin.as_view(), name='dashboard_login'),
    path('orders/', OrderListView.as_view(), name='dashboard_orders'),
    path('orders/<int:pk>/edit/', OrderEditView.as_view(), name='dashboard_orders_edit'),
    path('import-products/', PublicSchemaProductImport.as_view(), name='import_products'),
    path('store-products/', StoreProductListView.as_view(), name='store_products'),
    path('change-product-status/', ChangeProductStatus.as_view(), name='change_product_status'),
    path('create-product/', CreateProductView.as_view(), name='create_product'),
    path('edit-product/<int:pk>/', EditProductView.as_view(), name='edit_product'),
    path('brands/', BrandsListView.as_view(), name='brands_list_view'),
    path('create-brand/', AddBrandView.as_view(), name='create_brand'),
    path('edit-brand/<int:pk>/', EditBrandView.as_view(), name='edit_brand'),
    path('categories/', CategoryListView.as_view(), name='categories_list_view'),
    path('create-category/', AddCategoryView.as_view(), name='create_category'),
    path('edit-category/<int:pk>/', EditCategoryView.as_view(), name='edit_category'),
    path('blogs/', BlogsListView.as_view(), name='blogs_list_view'),
    path('create-blogs/', AddBlogsView.as_view(), name='create_blogs'),
    path('edit-blog/<int:pk>/', EditBlog.as_view(), name='edit_blog'),
    path('change-status/', ChangeStatus.as_view(), name='change_status'),

    path('onboardings/', OnboardingListView.as_view(), name='onboarding_list_view'),
    path('edit-onboardings/<int:pk>/', OnboardingEditView.as_view(), name='onboarding_edit_view'),
    path('delete-brand/<int:pk>/', DeleteBrand.as_view(), name='delete_brand'),
    path('delete-category/<int:pk>/', DeleteCategory.as_view(), name='delete_category'),
]

goshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from onboarding.views import PlanListView, OnboardingFormView, CreateOnboarding, SearchView


schema_view = get_schema_view(
    openapi.Info(
        title="Shopping API",
        default_version="v2",
        description="This Document has all the API endpoints for building setyour shop web pages.",
        terms_of_service="https://www.setyour.shop",
        contact=openapi.Contact(email="mohammed.sagheer95@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', SearchView.as_view(), name='search'),

    path('', PlanListView.as_view(), name='plans'),
    path("customer/", include('customers.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('onboarding/', include('onboarding.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('api/', include('restapis.urls')),
path(
            "swagger/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
    path('blogs/', include('cms.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls'))

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from products.views import AddProductFromPublicSchema


app_name = 'products'

urlpatterns = [
    path('add-product/', AddProductFromPublicSchema.as_view(), name='add_product'),
    # Add more product-related URL patterns as needed
]

products/models.py
import os

from django.db import models, connection
from django_extensions.db.fields import AutoSlugField
from tenant_schemas.utils import schema_context


# Create your models here.
from customers.abstract_model import TimeStamp


def get_upload_path(instance, filename):
    return os.path.join(connection.schema_name, filename)


class Brand(TimeStamp):
    title = models.CharField(max_length=300)
    slug = AutoSlugField(populate_from="title")
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Brand"
        verbose_name_plural = "Brands"


class Category(TimeStamp):
    title = models.CharField(max_length=300)
    slug = AutoSlugField(populate_from="title")
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Products(TimeStamp):
    STAND_ALONE_PRODUCT = 'stand_alone_product'
    PARENT_PRODUCT = 'parent_product'
    PRODUCT_TYPES = ((STAND_ALONE_PRODUCT, "Stand Alone Product"),
                     (PARENT_PRODUCT, "Parent Product"))

    title = models.CharField(max_length=300, db_index=True)
    description = models.TextField()
    image = models.ImageField(upload_to=get_upload_path, null=True)
    price = models.IntegerField()
    is_available = models.BooleanField(default=True)
    url = models.CharField(max_length=500, null=True, blank=True)
    brand = models.ForeignKey(Brand, null=True, on_delete=models.SET_NULL, related_name="brand_products")
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, related_name="categories_products")
    public_schema_product_id = models.IntegerField(default=False, db_index=True)
    product_type = models.CharField(max_length=30, choices=PRODUCT_TYPES, default=STAND_ALONE_PRODUCT)
    length = models.IntegerField(null=True)
    width = models.IntegerField(null=True)
    height = models.IntegerField(null=True)
    weight = models.IntegerField(null=True)
    stock = models.PositiveIntegerField(verbose_name="Stock available", default=0)
    search_keywords = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"

    def __str__(self):
        return self.title

    @property
    def get_image_url(self):
        if self.image:
            return self.image.url
        elif self.url:
            return self.url
        else:
            return ""

    def exists_in_basket(self, basket_id):
        from basket.models import BasketLine
        return BasketLine.objects.filter(product=self, basket_id=basket_id).exists()


    @property
    def imported(self):
        with schema_context(connection.schema_name):
            return Products.objects.filter(public_schema_product_id=self.id).exists()


class ProductImage(TimeStamp):
    image = models.ImageField(upload_to=get_upload_path, null=True)
    product = models.ForeignKey(Products, null=True, on_delete=models.CASCADE, related_name="product_image")
    is_cover_image = models.BooleanField(default=False)

    def __str__(self):
        return self.variant.name


    class Meta:
        verbose_name = "Product Image"
        verbose_name_plural = "Product Images"

dashboard/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from djrichtextfield.widgets import RichTextWidget

from cms.models import Blog
from onboarding.models import Onboarding
from products.models import Products, Brand, Category, ProductImage


class DashboardAdminForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())


class AddStoreProduct(forms.ModelForm):
    width = forms.IntegerField(initial=0)
    height = forms.IntegerField(initial=0)
    weight = forms.IntegerField(initial=0)
    length = forms.IntegerField(initial=0)
    stock = forms.IntegerField(initial=10, min_value=10)
    price = forms.IntegerField(min_value=0)

    class Meta:
        model = Products
        fields = ('title', 'description', 'price', 'brand', 'product_type', 'image','search_keywords',
                  'category', 'length', 'width', 'height', 'stock', 'weight', 'length')


class AddBrandForm(forms.ModelForm):

    class Meta:
        model = Brand
        fields = ('title',)

class AddCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title',)


    def clean_title(self):
        return self.cleaned_data['title'].capitalize()


class AddBlogForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget(config_name='default'))
    class Meta:
        model = Blog
        fields = ('title', 'body', 'status', 'cover_image')


class OnboardingEditForm(forms.ModelForm):
    class Meta:
        model = Onboarding
        fields = ('is_active', 'plan')

onboarding/forms.py
from django import forms
from django.core.exceptions import ValidationError

from customers.models import Client
from onboarding.models import Onboarding


class OnboardingForm(forms.ModelForm):
    schema_name = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=50)
    contact_number = forms.CharField(max_length=15)

    class Meta:
        model = Onboarding
        fields = ('schema_name', 'email', 'contact_number', 'first_name', 'last_name')

    def clean_schema_name(self,):
        schema_name = self.cleaned_data['schema_name']
        if Onboarding.objects.filter(schema_name=schema_name).exists():
            raise ValidationError('schema name already taken.')
        return schema_name

onboarding/views.py
import secrets
import string
import time

import stripe
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.db import connection, IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render

# Create your views here.
from django.urls import reverse
from django.views.generic import TemplateView, FormView, ListView
from elasticsearch_dsl import Q
from tenant_schemas.utils import schema_context

from basket.models import BasketLine
from customers.email import SendEmail
from customers.models import Client
from dashboard.views import TenantIsActive
from onboarding.forms import OnboardingForm
from onboarding.godaddy.client import GoDaddyClientHelper
from onboarding.models import Plan, Onboarding
from products.documents import ProductDocument
from products.models import Products


class PlanListView(TenantIsActive, ListView):
    model = Products
    template_name = 'onboarding/plans.html'
    tenant_homepage = 'onboarding/tenant_home.html'
    context_object_name = 'products'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        plans = Plan.objects.filter(is_active=True).order_by('id')
        context = super().get_context_data(**kwargs)
        context['plans'] = plans
        context['tenant'] = connection.schema_name
        if connection.schema_name != 'public':
            with schema_context(connection.schema_name):
                context['basket_lines'] = BasketLine.objects.filter(basket_id=self.request.basket).count()
        return context

    def get_queryset(self):
        if connection.schema_name != 'public':
            return Products.objects.filter(is_available=True)
        return Plan.objects.filter(is_active=True).order_by('id')


    def get_template_names(self):
        if connection.schema_name == 'public':
            return self.template_name
        return self.tenant_homepage


class SearchView(TemplateView):
    template_name = 'onboarding/tenant_home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        q = self.request.GET.get('q')
        if q:
            response = ProductDocument().response(q)
            context['products'] = response
            context['searchterm'] = q
        elif self.request.GET.get('price'):
            price = int(self.request.GET.get('price'))
            response = ProductDocument().filter_by_price(price)
            context['products'] = response
        elif self.request.GET.get('category'):
            category = self.request.GET.get('category')
            response = ProductDocument().filter_by_category(category)
            context['products'] = response
        return context




class OnboardingFormView(FormView):
    template_name = 'onboarding/onboarding_form.html'
    form_class = OnboardingForm
    plan = None

    def form_valid(self, form):
        clientobj = form.save(commit=False)
        clientobj.domain_url = clientobj.schema_name + "." + settings.PUBLIC_DOMAIN_URL
        self.plan = Plan.objects.get(slug=self.kwargs.get('slug'))
        clientobj.plan = self.plan

        stripe.api_key = settings.STRIPE_SECRET_KEY
        if settings.IS_PRODUCTION:
            success_url = f"http://{settings.PUBLIC_DOMAIN_URL}/onboarding/success/"
        else:
            success_url = f"http://localhost:8000/onboarding/success/"
        session = stripe.checkout.Session.create(
            line_items=[
                {
                    "price_data": {
                        "currency": "gbp",
                        "product_data": {"name": self.plan.title},
                        "unit_amount": self.plan.price * 100,
                    },
                    "quantity": 1,
                },
            ],
            mode="payment",
            success_url=success_url + "{CHECKOUT_SESSION_ID}/",
            cancel_url="http://localhost:8000/cancel",
        )
        clientobj.session_id = session.id
        clientobj.save()
        return redirect(session.url)


class CreateOnboarding(TemplateView):
    template_name = "onboarding/payment_success.html"

    def get_context_data(self, **kwargs):
        onboarding = Onboarding.objects.get(session_id=self.kwargs.get('slug'))
        if onboarding.is_active is False:
            if settings.IS_PRODUCTION:
                godaddy = GoDaddyClientHelper()
                schema_name = onboarding.schema_name
                godaddy.add_cname_to_dns(schema_name)

            client = Client.objects.create(domain_url=onboarding.domain_url.lower(), schema_name=onboarding.schema_name.lower())
            onboarding.is_active = True
            onboarding.client = client
            onboarding.save()
            with schema_context(onboarding.schema_name):
                try:
                    user = User.objects.create(username='admin@setyour.shop')
                    characters = string.ascii_letters + string.digits
                    keyword = ''.join(secrets.choice(characters) for _ in range(8))
                    user.set_password(keyword)
                    user.is_superuser = True
                    user.is_staff = True
                    user.save()
                    site = Site.objects.first()
                    site.domain = onboarding.domain_url
                    site.save()
                    SendEmail().send_onboarded_admin_email(site.domain, keyword, onboarding.email)
                except IntegrityError as e:
                    pass
        context = super().get_context_data()
        context['website_url'] = onboarding.domain_url
        context['products'] = Products.objects.filter(is_available=True)
        context['schema_name'] = onboarding.schema_name

        return context

products/views.py
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from tenant_schemas.utils import schema_context

from products.models import Products


class AddProductFromPublicSchema(View):

    @csrf_exempt
    def post(self, request):
        data = request.POST
        schema_name = data.get("schema_name")
        product = Products.objects.get(id=data.get("id"))
        with schema_context(schema_name):
            if Products.objects.filter(title=product.title).exists():
                return JsonResponse({"message": "Error"}, status=400)
            product_dictionary = {"title": product.title,"public_schema_product_id":product.id,
                                  "description": product.description, "url": product.get_image_url,
                                  "is_available": product.is_available, "price": product.price}
            Products.objects.create(**product_dictionary)
        return JsonResponse({"message": "Success"})

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>Home:Products</title>
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <link href="{% static 'css/sidebars.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
</head>
<body>
<main>
 <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-4">Admin Dashboard</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="{% url 'dashboard:dashboard_home' %}" class="nav-link text-white {% if request.resolver_match.url_name == 'dashboard_home'%}active{% endif %}" aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"/></svg>
          Home
        </a>
      </li>
      <li>
        <a href="{% url 'dashboard:dashboard_orders' %}" class="nav-link text-white {% if request.resolver_match.url_name == 'dashboard_orders' %}active{% endif %}">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"/></svg>
          Orders
        </a>
      </li>
        <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed nav-link text-white" data-bs-toggle="collapse" data-bs-target="#product-collapse" aria-expanded="false">
          Products
        </button>
        <div class="collapse {{collapse_open}}" id="product-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
           {% if request.tenant.schema_name != 'public' %} <li><a href="{% url 'dashboard:import_products' %}" class="nav-link text-white rounded {% if request.resolver_match.url_name == 'import_products' %}active{% endif %}">Import Products</a></li>{% endif %}
            <li><a href="{% url 'dashboard:store_products' %}" class="nav-link text-white rounded {% if request.resolver_match.url_name == 'store_products' %}active{% endif %}">Store Products</a></li>
            <li><a href="{% url 'dashboard:brands_list_view' %}" class="nav-link text-white rounded {% if request.resolver_match.url_name == 'brands_list_view' %}active{% endif %}">Brands</a></li>
            <li><a href="{% url 'dashboard:categories_list_view' %}" class="nav-link text-white rounded {% if request.resolver_match.url_name == 'categories_list_view' %}active{% endif %}">Categories</a></li>
          </ul>
        </div>
      </li>
      <li>
          {% if request.tenant.can_publish_cms %}
          <a href="{% url 'dashboard:blogs_list_view' %}" class="nav-link text-white {% if request.resolver_match.url_name == 'blogs_list_view' %}active{% endif %}">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"/></svg>
          Blogs
        </a>
          {% endif %}
      </li>
        <li>
          {% if request.tenant.schema_name == 'public' %}
          <a href="{% url 'dashboard:onboarding_list_view' %}" class="nav-link text-white {% if request.resolver_match.url_name == 'onboarding_list_view' %}active{% endif %}">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"/></svg>
          Onboarding
        </a>
          {% endif %}
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>{{request.user.username}}</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="{% url 'customers:logout' %}">Sign out</a></li>
      </ul>
    </div>
  </div>
 <div class="b-example-divider"></div>

{% block body %}

{% endblock %}
</main>
</body>
<script>
    /* global bootstrap: false */
(function () {
  'use strict'
  var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
  tooltipTriggerList.forEach(function (tooltipTriggerEl) {
    new bootstrap.Tooltip(tooltipTriggerEl)
  })
})()




    $("#import_product").on("click", function(){
        let checkboxlist = [];
        $('input[name="product"]').each(function(){
            if((!$(this).attr("disabled")) && ($(this).prop("checked"))){
                checkboxlist.push($(this).attr("product_id"));
                $(this).prop("disabled",true);
            }
        })
        data = {"ids": checkboxlist}
        $.ajax({
                url: "{% url 'dashboard:import_products' %}",
                method: "POST",
                dataType: "json",
                data: data,
                success: function(response) {
                toastr.success('product imported');
                },
                error: function(xhr, status, error) {
                    console.error("AJAX Request Error:", status, error);
                }
            });
    });

</script>
{% block script %}
{% endblock %}
</html>

templates/dashboard/onboardings.html
{% extends 'dashboard/base.html' %}
{% block title %}
    <title>Dashboard: {{metadata_value}}</title>
    {% endblock %}
{% block body %}
<div class="container" style="overflow: auto;">
<div class="row">

  <div class="mx-auto col-sm-6" style="margin-top: 40px">
    <form action="." method="get" autocomplete="off">
      <div class="input-group">
        <input type="text" name="title" class="form-control" placeholder="Search using schema name" {% if query %}value="{{query}}" {% endif %}>
      </div>
    </form>
  </div>

</div>
<div class="d-flex" style="width:100%">

  <table class="table">
    <thead>
      <tr>
        <th scope="row"><input type="checkbox"></th>
        <th scope="col">Schema Name</th>
        <th scope="col">Status</th>
        <th scope="col">Plan</th>
        <th scope="col">Created at</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
      </tr>
    </thead>
      <tbody>
      {% for tenant in tenants %}
      <tr>
        <th scope="row"><input type="checkbox"></th>
        <td>{{tenant.schema_name}}</td>
        <td>{% if tenant.is_active %}Active{% else %}Inactive{% endif %}</td>
        <td>{{tenant.plan}}</td>
        <td>{{tenant.created_at|date:'d/m/Y'}}</td>
          <td><a href="{% url 'dashboard:onboarding_edit_view' pk=tenant.id%}" type="button" class="btn btn-primary">Edit</a> </td>
<!--          <td><a href="#" type="button" class="btn btn-danger">Delete</a> </td>-->
      </tr>
      {% endfor %}
      </tbody>
  </table>
</div>
</div>
    {% endblock %}

templates/dashboard/products.html
{% extends 'dashboard/index.html' %}
{% block title %}
    <title>Dashboard: {{page_title}}</title>
    {% endblock %}
{% block body %}
<div class="content-body">
    <!-- row -->
    <div class="container-fluid">

        <div class="row">
            <div class="col-xl-6 col-xxl-12">
                <div class="card">
                    <div class="tab-pane active show fade">
                        <div class="tab-pane" id="Today" role="tabpanel">
                            <div class="table-responsive">
                                <table class="table table-responsive-md card-table transactions-table">
    <thead>
      <tr>
        <th scope="row">Sl No</th>
        <th scope="col">Product</th>
        <th scope="col">Thumbnail</th>
        <th scope="col">Price</th>
        <th scope="col">Type</th>
        {% if request.resolver_match.url_name == 'store_products' %}
        <th scope="col">Show on Website</th>
        <th scope="col">Brand</th>
        <th scope="col">Category</th>
        {% endif %}
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>

    {% for product in items %}
      <tr>
        <th scope="row"><input name="product" product_id="{{product.id}}" type="checkbox" {% if request.resolver_match.url_name == 'import_products' and  product.imported %}checked disabled{% endif %}></th>
        <td>{{product.title}}</td>
        <td><img src="{{product.get_image_url}}" style="width:50px;height:50px"> </td>
        <td>£ {{product.price}}</td>
        <td>{{product.get_product_type_display}}</td>
        {% if request.resolver_match.url_name == 'store_products' %}
        <td><input name="show_on_website" type="checkbox" product_id="{{product.id}}" {% if product.is_available %}checked{% endif %}></td>
        <td>{{product.brand.title}}</td>
        <td>{{product.category.title}}</td>
        <td><a href="{% url 'dashboard:edit_product' pk=product.id %}" type="button" class="btn btn-primary">Edit</a> </td>
        {% endif %}
      </tr>
    {% endfor %}
      <!-- Add more rows for each order -->
    </tbody>
  </table>



                            </div>

                        </div>
                        <div class="pagination-container" style="text-align: center;">
<div class="pagination text-center">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1{% if query%}&name={{query}}{% endif %}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}{% if query%}&name={{query}}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if query%}&name={{query}}{% endif %}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}{% if query%}&name={{query}}{% endif %}">last &raquo;</a>
        {% endif %}
    </span>
</div>
    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--**********************************
    Content body end
***********************************-->


{% endblock %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
<script>
    toastr.options = {
  "closeButton": false,
  "debug": false,
  "newestOnTop": false,
  "progressBar": true,
  "positionClass": "toast-bottom-center",
  "preventDuplicates": false,
  "onclick": null,
  "showDuration": "300",
  "hideDuration": "1000",
  "timeOut": "1000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut"
}

  $('input[name="show_on_website"]').on("change", function(e){

    data = {"status": $(this).prop("checked"), "product_id": $(this).attr("product_id")};
        $.ajax({
                url: "{% url 'dashboard:change_product_status' %}",
                method: "POST",
                dataType: "json",
                data: data,
                success: function(response) {
                toastr.info('product marked');
                },
                error: function(xhr, status, error) {
                    console.error("AJAX Request Error:", status, error);
                }
            });
  })

</script>
{% endblock %}